version: '3'
services:
  postgres:
    image: 'postgres:latest'
    # Database name, user name, user password are taken from those environment variables.
    # Database is created there and no need to run rails db:create.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=sittme_dev
      - POSTGRES_USER=sittme_dev
      - POSTGRES_PASSWORD=sittme_dev
    expose:
      - 5432
    ports:
      - '5432:5432'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=sittme_dev
      - POSTGRES_USER=sittme_dev
      - POSTGRES_PASSWORD=sittme_dev
      - RAILS_ENV=development
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
